### ISSUE TITLE
RuntimeError when training

### ISSUE THREAD

**Issue by skywo1f** [kewellcjj/pytorch_style_transfer#3]
I was running the training script but got:
Traceback (most recent call last):
  File "neural_style.py", line 231, in <module>
    main()
  File "neural_style.py", line 225, in main
    train(args)
  File "neural_style.py", line 70, in train
    style = torch.stack(style_batch).to(device)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 4 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:711
any ideas?

**Comment by kewellcjj** [comment]
I think "Got 3 and 4 in dimension 1" means the style images in the same ```style_batch``` have a different number of channels so the ```stack``` does not work here. Not an expert, but I think most images have three channels for RGB. Make sure all images have the same amount of channels, or you need to find a way to convert the 4-channel image to 3 channels.

**Comment by skywo1f** [comment]
thanks! yeah, I had both png's and jpg's in my style folder. I picked one, but now I am getting 
  File "neural_style.py", line 231, in <module>
    main()
  File "neural_style.py", line 225, in main
    train(args)
  File "neural_style.py", line 72, in train
    features_style = vgg(utils.normalize_batch(style))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pi/pytorch-multiple-style-transfer/vgg.py", line 30, in forward
    h = self.slice1(X)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at /home/pi/pytorch/aten/src/TH/THGeneral.cpp:188


I tried setting the --batch-size 1, but that didnt help. I am trying to train this on a Raspberry pi 4 with 4gb ram. Is that too optimistic? are there any other flags that I should set?
I have 103 images in my style folder

**Comment by skywo1f** [comment]
removing all but one image gave me a different error:
Traceback (most recent call last):
  File "neural_style.py", line 231, in <module>
    main()
  File "neural_style.py", line 225, in main
    train(args)
  File "neural_style.py", line 106, in train
    total_loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /home/pi/pytorch/aten/src/TH/THGeneral.cpp:201

**Comment by kewellcjj** [comment]
What are your command arguments, like how large are your style images and do you scale them? Seems you are running out of memory. 

FYI, I trained my model on a GPU with 8g of ram. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skywo1f** [comment]
python3 neural_style.py train --dataset /home/pi/pytorch-multiple-style-transfer/ --style-image syles/ --save-model-dir /home/pi/pytorch-multiple-style-transfer/save-dir/ --cuda 0 --batch-size 1 --style-size 10

seemed to work thanks! though it took a while. I will keep playing with it

**Comment by skywo1f** [comment]
By the way, that last command took about an hour to train.
I was able to then use the neural_style.py script on it, with 
python3 neural_style.py train --dataset /home/pi/pytorch-multiple-style-transfer/ --style-image style/ --save-model-dir /home/pi/pytorch-multiple-style-transfer/save-dir/ --cuda 0 --batch-size 1 --style-size 10
which gave me an output, though it just looks like a bunch of noise

**Comment by kewellcjj** [comment]
What kind of output? Also ```style-size``` is the size of style-image, so 10 seems to be too small to learn a meaningful style. Or if you actually mean to learn styles from 10 images?

**Comment by kewellcjj** [comment]
Consider the initial issue solved. Discussion can be continued here or by opening a new issue.
